padmex/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

app_name = 'padmex'

urlpatterns = [
    # /padmex/
    path('', views.IndexView.as_view(), name='index'),
    path('olimpicas', views.VerOlimpicas.as_view(), name="olimpicas"),
    path('residenciales', views.VerResidenciales.as_view(), name="residenciales"),
    path('productos', views.VerProductos.as_view(), name="productos"),
    re_path(r'^productos/(?P<pk>[0-9]+)/$', views.DetailViews.as_view(), name='detail'),
    #path(r'productos/add/$', views.UserCreate.as_view(), name='cliente-add'),
]

proyectoWeb_padmex/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

from accounts.views import (login_view, register_view, logout_view)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('padmex.urls')),
    re_path(r'^login/', login_view, name='login'),
    re_path(r'^logout/', login_view, name='logout'),
]

accounts/models.py
from django.db import models

# Create your models here.

padmex/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.

class Cliente(models.Model):
    nombre = models.CharField(max_length=100)
    usuario = models.CharField(max_length=100)
    passwd = models.CharField(max_length=20)
    correo = models.CharField(max_length=200, default=" ")
    telefono = models.CharField(max_length=20, default=" ")
    def __str__(self):
        return self.nombre + ' - ' + self.usuario + ' - ' + self.correo + ' - ' + self.telefono
    def _get_pk_val(self, meta=None):
        return reverse('padmex:url', kwargs={'pk': self.pk})

class Producto(models.Model):
    nombreProd = models.CharField(max_length=200)
    descripcionProd = models.CharField(max_length=2000)
    precio = models.CharField(max_length=20)
    imagen = models.CharField(max_length=200, default="")
    def __str__(self):
        return self.nombreProd + ' - ' + self.precio

class Pedido(models.Model):
    cliente_FK = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(
        default = timezone.now
    )
    status = models.CharField(max_length=20)
    def __str__(self):
        return self.cliente_FK.nombre + ' - ' + self.fecha.strftime('%Y-%M-%d') + ' - ' + self.status

class Detalle(models.Model):
    pedido_FK = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    producto_FK = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad = models.CharField(max_length=20)
    def __str__(self):
        return  self.producto_FK.nombreProd + ' - ' + self.cantidad

class Cita(models.Model):
    cliente_FK = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    fecha = models.DateTimeField(
        default=timezone.now
    )
    status = models.CharField(max_length=20, default="Por atender")
    def __str__(self):
        return self.cliente_FK + ' - ' + self.fecha + ' - ' + self.status

accounts/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)

User = get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        #user_qs = User.objects.filter(username=username)
        #if user_qs.count() == 1:
         #   user = user.qs.first()
        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
            if not user.is_active:
                raise forms.ValidationError("This user is no longer active")
        return super(UserLoginForm, self).clean(*args, **kwargs)

padmex/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

accounts/views.py
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,
)
from django.shortcuts import render

from .forms import UserLoginForm

# Create your views here.

def login_view(request):
    title = "Login"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        print(request.user.is_authenticated)
    return render(request, "form.html", {"form": form, "title": title})

def register_view(request):
    return render(request, "form.html", {})

def logout_view(request):
    logout(request)
    return render(request, "form.html", {})

padmex/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Detalle, Cliente, Producto


class IndexView(generic.ListView):
    template_name = 'padmex/index.html'
    def get_queryset(self):
        return Detalle.objects.all()

class VerOlimpicas(generic.ListView):
    model = Detalle
    template_name = 'padmex/olimpicas.html'

class VerResidenciales(generic.ListView):
    template_name = 'padmex/residenciales.html'
    def get_queryset(self):
        return Detalle.objects.all()

class VerProductos(generic.ListView):
    template_name = 'padmex/productos.html'
    def get_queryset(self):
        return Detalle.objects.all()

class DetailViews(generic.DetailView):
    model = Producto
    template_name = 'padmex/producto_form.html'

padmex/templates/padmex/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Padmex{% endblock %}</title>
    <link  rel="stylesheet" type="text/css" href="{% static 'padmex/css/style.css' %}"/>
    <link rel="icon" type="text/css" href="{% static 'padmex/img/padmex_logo.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'padmex/css/materialize.min.css' %}"/>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <style>
        .logo {
	height: 50px;
	margin: 7px;
}

.navInicio {
	background: transparent !important;
}

.carrito {
	margin-top: 20px;
}

body {
/* Ubicación de la imagen */
background-image: url(../../static/padmex/img/fondo1.jpg);
/* Para dejar la imagen de fondo centrada, vertical y horizontalmente */
background-position: center center;
/* Para que la imagen de fondo no se repita */
background-repeat: no-repeat;
/* La imagen se fija en la ventana de visualización para que la altura de la imagen no supere a la del contenido */
background-attachment: fixed;
/* La imagen de fondo se reescala automáticamente con el cambio del ancho de ventana del navegador */
background-size: cover;
/* Se muestra un color de fondo mientras se está cargando la imagen de fondo o si hay problemas para cargarla */
background-color: black;

animation: cambiarfondo 20s;
animation-iteration-count: infinite;

}

@keyframes cambiarfondo {
	0% {
		background-image: url(../../static/padmex/img/fondo1.jpg);
	}
	30% {
		background-image: url(../../static/padmex/img/fondo1.jpg);
	}
	35% {
		background-image: url(../../static/padmex/img/p3.jpg);
	}
	65% {
		background-image: url(../../static/padmex/img/p3.jpg);
	}
	70% {
		background-image: url(../../static/padmex/img/p9.jpg);
	}
	95% {
		background-image: url(../../static/padmex/img/p9.jpg);
	}
}
    </style>

</head>
<body>
    <div class="navbar-fixed">
	<nav class="navInicio">

		<div class="row">
			<div class="col m4 s12">
				<a href="{% url 'padmex:index' %}" class="brand-logo"><img class="logo" src="{% static 'padmex/img/padmex_logo.png' %}"></a>
			</div>
			<div class="col m4 s12">
				<a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
				<ul class="right hide-on-med-and-down">
	    			<li><a href="{% url 'padmex:olimpicas' %}">Albercas Olímpicas</a></li>
	    			<li><a href="{% url 'padmex:residenciales' %}">Albercas Residenciales</a></li>
	    			<li><a href="{% url 'padmex:productos' %}">Productos</a></li>
	    		</ul>
			</div>
			<div class="col m4 s12">
				<ul class="right hide-on-med-and-down">
	    			<li><a href="#">Sign In/Up</a></li>
	    			<li><a href="#"><img class="carrito" src="{% static 'padmex/img/carritoComprasB.png' %}"></a></li>
					<li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Mostrar más<i class="material-icons right">arrow_drop_down</i></a></li>
	    		</ul>
			</div>
		</div>
	</nav>
	</div>

	<ul class="sidenav" id="mobile-demo">
		<li><a href="{% url 'padmex:olimpicas' %}">Albercas Olímpicas</a></li>
		<li><a href="badges.html">Albercas Residenciales</a></li>
		<li><a href="collapsible.html">Productos</a></li>
		<li class="divider"></li>
		<li><a href="#">Sing In/Up</a></li>
		<li><a href="#">Carrito</a></li>
		<li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Más<i class="material-icons right">arrow_drop_down</i></a></li>
	</ul>

	<ul id="dropdown1" class="dropdown-content">
		<li><a href="#!">Nosotros</a></li>
		<li><a href="#!">Contacto</a></li>
		<li><a href="#!">Ubicaciones</a></li>
	</ul>

	<ul id="dropdown2" class="dropdown-content">
		<li><a href="#!">Nosotros</a></li>
		<li><a href="#!">Contacto</a></li>
		<li><a href="#!">Ubicaciones</a></li>
	</ul>

    {% block body %}
    {% endblock %}

</body>
<script type="text/javascript" src="../../static/padmex/js/jquery.js"></script>
<script type="text/javascript" src="../../static/padmex/js/materialize.min.js"></script>
<script type="text/javascript" src="../../static/padmex/js/app.js"></script>
</html>

padmex/templates/padmex/details.html
{{ cliente }}

padmex/templates/padmex/detalles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Detalles</h1>
    {% for detalle in object_list %}
        <p>{{ detalle.id }}</p>
        <p>{{ detalle.producto_FK.descripcionProd }}</p>
        <p>{{ detalle.producto_FK.precio }}</p>
    {% endfor %}
</body>
</html>

padmex/templates/padmex/form-template.html
{% for field in form %}

    <p>{{ field.errors }}</p>

{% endfor %}

padmex/templates/padmex/index.html
{% extends 'padmex/base.html' %}
{% block body %}
    <h1> page</h1>
{% endblock %}

padmex/templates/padmex/olimpicas.html
{% extends 'padmex/base.html' %}
{% block title %}Albercas olímpicas{% endblock %}
{% block body %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">
	<title>PadMex | Alberca Olímpica</title>
	<link rel="icon" type="text/css" href="img/padmex_logo.png">
	<link rel="stylesheet" type="text/css" href="css/materialize.min.css">
	<link rel="stylesheet" type="text/css" href="css/style.css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
	<body background="img/AO/img.jpg">

		<div class="navbar-fixed">
			<nav class="azul">

				<div class="row">
					<div class="col m4 s12">
						<a href="index.html" class="brand-logo"><img class="logo" src="img/padmex_logo.png"></a>
					</div>
					<div class="col m4 s12">
						<a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
						<ul class="right hide-on-med-and-down">
							<li><a href="albercaOlimpica.html">Alberca Olímpica</a></li>
							<li><a href="albercaResidencial.html">Alberca Residencial</a></li>
							<li><a href="productos.html">Productos</a></li>
						</ul>
					</div>
					<div class="col m4 s12">
						<ul class="right hide-on-med-and-down">
							<li><a href="#">Sing In/Up</a></li>
							<li><a href="#"><img class="carrito" src="img/carritoComprasB.png"></a></li>
							<li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Mostrar más<i class="material-icons right">arrow_drop_down</i></a></li>
						</ul>
					</div>
				</div>
			</nav>
		</div>

		<ul class="sidenav" id="mobile-demo">
			<li><a href="albercaOlimpica.html">Alberca Olímpica</a></li>
			<li><a href="albercaResidencial.html">Alberca Residencial</a></li>
			<li><a href="productos.html">Productos</a></li>
			<li class="divider"></li>
			<li><a href="#">Sing In/Up</a></li>
			<li><a href="#">Carrito</a></li>
			<li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Más<i class="material-icons right">arrow_drop_down</i></a></li>
		</ul>

		<ul id="dropdown1" class="dropdown-content">
			<li><a href="nosotros.html">Nosotros</a></li>
			<li><a href="contacto.html">Contacto</a></li>
			<li><a href="ubicaciones.html">Ubicaciones</a></li>
		</ul>

		<ul id="dropdown2" class="dropdown-content">
			<li><a href="nosotros.html">Nosotros</a></li>
			<li><a href="contacto.html">Contacto</a></li>
			<li><a href="ubicaciones.html">Ubicaciones</a></li>
		</ul>

		<main>


			<div class="container">
				<div class="row">
					<div class="col s12 cuadro negro fjo">
						<h4>Albercas Olimpicas</h4>
					</div>
				</div>
				<div class="row">
					<div class="slider">
						<ul class="slides">
							<li>
								<img src="img/AO/img1.jpg">
								<div class="caption center-align">
									<h3>This is our big Tagline!</h3>
									<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
								</div>
							</li>
							<li>
								<img src="img/AO/img7.jpg">
								<div class="caption left-align">
									<h3>Left Aligned Caption</h3>
									<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
								</div>
							</li>
							<li>
								<img src="img/AO/img3.jpg">
								<div class="caption right-align">
									<h3>Right Aligned Caption</h3>
									<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
								</div>
							</li>
							<li>
								<img src="img/AO/img4.jpg">
								<div class="caption right-align">
									<h3>Right Aligned Caption</h3>
									<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
								</div>
							</li>
							<li>
								<img src="img/AO/img5.jpg">
								<div class="caption center-align">
									<h3>This is our big Tagline!</h3>
									<h5 class="light grey-text text-lighten-3">Here's our small slogan.</h5>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>

			<div id="olimpica" class="parallax-container">
				<div class="parallax"><img src="img/AO/img.jpg"></div>
				<div class="section container tranparent">
					<div class="row">
						<div class="row">
							<div class="container col m12 s12">
								<p class="cuadro2 blanco">Se ha dedicado al diseño, construcción, y suministro  de  equipo para Albercas Olímpicas, SemiOlímpicas y de uso particular en condominios, residencias, clubes Deportivos, Gobierno. Distribuimos equipos de las firmas mas importes de Europa y América garantizando equipos de alta tecnologia contando  con  una linea  extensa de productos.</p>
							</div>
							<div class="col s12">
								<div class="row">
									<div class="col s12">
										<center>
											<p class="boton negro"><a class="lb" href="contacto.html">¡Haz una cita!</a></p>
										</center>
									</div>
									<div class="col s12">
										<center>
											<p class="boton negro"><a class="lb" href="galeria.html">Ver galería</a></p>
										</center>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>


			<div class="parallax-container">
				<div class="parallax"><img src="img/AO/img.jpg"></div>
				<div class="container col s12">
					<img class="img" src="img/AO/img8.jpg" >
				</div>
			</div>


		</main>

	</body>
	<script type="text/javascript" src="js/jquery.js"></script>
	<script type="text/javascript" src="js/materialize.min.js"></script>
	<script type="text/javascript" src="js/app.js"></script>
	</html>
{% endblock %}

padmex/templates/padmex/producto_form.html
{% extends 'padmex/base.html' %}
{% block title %}Comprar{% endblock %}
{% block body %}
    <h1>Comprar</h1>

        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'padmex/form-template.html' %}
            <div class="row">
                <form class="col s12">
                  <div class="row">
                    <div class="input-field col s12">
                      <textarea id="textarea1" class="materialize-textarea"></textarea>
                      <label for="textarea1">Textarea</label>
                    </div>
                        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                            <i class="material-icons right">send</i>
                        </button>
                  </div>
                </form>
            </div>
        </form>

        <p>{{ producto.descripcionProd}}</p>

{% endblock %}

padmex/templates/padmex/productos.html
{% extends 'padmex/base.html' %}
{% block title %}Productos{% endblock %}
{% block body %}
    <h1>Detalles</h1>
    {% for detalle in object_list %}
    <div class="row">
        <div class="col s3">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" src="images/office.jpg" alt="imgprod1">
                </div>
                <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4">{{detalle.producto_FK.nombreProd }}<i class="material-icons                               right">more_vert</i></span>
                    <p><a href="{% url 'padmex:detail' detalle.pk %}">Comprar</a></p>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">{{                           detalle.producto_FK.nombreProd }}<i                           class="material-icons right">close</i></span>
                    <p>{{ detalle.producto_FK.descripcionProd }}</p>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}

{% endblock %}

padmex/templates/padmex/registrar.html
{% extends 'padmex/base.html' %}
{% block title %}Crear nueva cuenta{% endblock %}
{% block body %}
    <form method="post">
        {% csrf_token %}

    </form>

{% endblock %}

padmex/templates/padmex/registrationForm.html
{% extends 'padmex/base.html' %}
{% block title %}Crear nueva cuenta{% endblock %}
{% block body %}
    <h1>Crear nueva cuenta</h1>

        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'padmex/form-template.html' %}
            <div class="row">
                <form class="col s12">
                  <div class="row">
                    <div class="input-field col s12">
                      <textarea id="textarea1" class="materialize-textarea"></textarea>
                      <label for="textarea1">Textarea</label>
                    </div>
                        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
                            <i class="material-icons right">send</i>
                        </button>
                  </div>
                </form>
            </div>
        </form>



{% endblock %}

padmex/templates/padmex/residenciales.html
{% extends 'padmex/base.html' %}
{% block title %}Albercas residenciales{% endblock %}
{% block body %}

{% endblock %}

templates/form.html
{% extends 'padmex/base.html' %}
{% block title %}PRUEBAFORMAUTH{% endblock %}
{% block body %}
    <div class="row">
        <form class="col s12" method="post" action='' enctype="multipart/form-data">
            {% csrf_token %}
            <h1>{{ title }}</h1>
            {{ form }}
            <div class="row">
                <input type="submit" class="btn waves-effect waves-light" value="{{ title }}">
            </div>
        </form>
    </div>

{% endblock %}